services:
  node:
    image: ${DOCKER_REGISTRY-}cwate-sb
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "80"
    environment:
      - ENVIRONMENT=production
      - CONNECTION_STRING=
    volumes:
      - ./run/data/:/data
    restart: unless-stopped
  proxy:
    image: cr.czompicloud.hu/czsoft/reverse-proxy:1.0.1-1.25.4
    depends_on:
      - node
    ports:
      - "5000:4000"
    restart: unless-stopped